### ISSUE TITLE
Debian packages lack dependency on java

### ISSUE THREAD

**Issue by banholzer** [openhab/openhab-linuxpkg#123]
Debian packages are missing a required dependency on java. Following installation steps on a blank debian minimal works but daemon is unable to start because java is missing.

I think a "Depends: java8-runtime-headless" should be added.

**Comment by BClark09** [comment]
Hi @banholzer,

Unfortunately, we can't add Java as a dependency because many people opt to install it as manually, a Debian dependancy will block the install of openHAB until a package is installed. At one point, the openHAB package recommended Java but was undone by https://github.com/openhab/openhab-linuxpkg/pull/75, after this the Debian package only recommends.

We found that even with "recommends", apt would install a Java automatically for people even if they had a manually installed version. https://community.openhab.org/t/systeminfo-initialization-error-on-pine64/11726/25?u=benjy

Do you agree with this reasoning? If not, is there a suitable compromise?

**Comment by ThomDietrich** [comment]
Slightly off-topic: The post- or pre-install script could check for an existing java runtime and take action or at least notify the end-user

**Comment by banholzer** [comment]
@BClark09 I dont think many peolple want to manually install Java on a Debian system. I think everyone would accept installing openjdk-9-jre-headless or another openjdk as long as it works - I think nobody chooses Oracle-Java as long he/she isn't forced to by the application. And nobody installs Java manually if there is a package which automatically upgrades on security issues.

The suggestion of @ThomDietrich would be a workaround - but usually a Debian package holds all needed dependencys and is running without further action.

**Comment by mstormi** [comment]
@banholzer Sorry but no quite the opposite is true. The most common openHAB install is not on plain debian but on openHABian and/or Raspis, and that's where the recommended Java to use is Zulu which in fact has to be installed manually. openHABian will automate that but Java is not available as .deb packages.

**Comment by mstormi** [comment]
No it isn't. Those packages you refer to are for x86 only, and that's my point: while you're apparently only interested in installing the x86 version (probably because you use that HW), the majority of openHABian users uses ARM hardware. So since we're talking openHABian in generalhere (and not on x86) and need to decide on one or the other, we should decide in favor of the majority.
If you dislike that you're free to submit a PR to provide a package implementation for x86 users.

**Comment by BClark09** [comment]
To add there isn't an official and up-to-date package repository for zulu-embedded-8, and this must be installed with a zip file.

Nonetheless, I agree that a user must be made aware that there is no suitable version of Java installed when installing openHAB (as it is fairly useless without it). I will look to add the same JAVA finding mechanism _postinst_ to inform the user that there is action needed here.

**Comment by ThomDietrich** [comment]
@BClark09 this might be of interest: http://zulu.org/forum/thread/please-make-zulu-debian-packages-provide-java-runtime-headless
