### ISSUE TITLE
apt-repo2 testing is older than stable

### ISSUE THREAD

**Issue by klaernie** [openhab/openhab-linuxpkg#82]
Hi there,

I installed openHAB for the first time and decided to go for testing packages, as they promise a trade off between freshness and stability. Two days later I noticed that openhab.org offers downloads for version 2.1 where I had 2.0.0-RC1 installed.

My expectation was, that the versions in the repositories always fulfill `unstable >= testing >= stable`.
If this promise is not fulfilled the documentation should state that testing and stable repositories should be active at the same time (the only other possibility interpreting the docs).

Thanks and kind regards,
Andre

(Follow-up to openhab/openhab-distro#545)

**Comment by BClark09** [comment]
Hi Andre,

Thanks for reporting this, I was unaware that the testing repo still did not contain the latest stable release. You'll be pleased to know that as of #62 stable NEW stable releases will be incorporated in the testing and unstable builds as you expect.

2.0.0-RC1 is actually pretty old, as there was no testing/RC phase before the release of 2.1.0. There are a couple of breaking changes between it and 2.1.0 as well. Therefore, I would be keen to add a 2.1.0 version to it straight away. I'm currently unsure the best way to go about this.

@ThomDietrich, @kaikreuzer. I'm thinking of adding a 2.1.0-2 version that belongs to the testing distribution only. Here I would:

 1. Make a PR here, adding a 2.1.0-2 version to testing only.
2.  Run the build on cloudbees to publish a signed .deb file to Artifactory.
3. Run the artifactory -> bintray tool to get the testing repo updated with 2.1.0-2

Why 2.1.0-2? Because the Linux package would include tools not seen in 2.1.0-1 but are linuxpkg specific, such as the new openhab-cli. Otherwise the actual distribution of 2.1.0 will be identical.

**Comment by BClark09** [comment]
Hi @klaernie, I have added a PR which will help me resolve the issue. I hope to test it and then implement it by the end of tomorrow.

**Comment by BClark09** [comment]
Hi @klaernie, the testing repo now contains version 2.1.0-2. Which is the 2.1.0 distribution plus the latest apt package fixes.

**Comment by klaernie** [comment]
Hi @BClark09, sorry for the late reply. Thanks a lot, works nicely!
